/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lanegame;

import java.awt.event.ActionListener;

/**
 *
 * @author Daniel
 */
public class MainMenu extends javax.swing.JFrame implements ActionListener {

    /**
     * Creates new form MainMenu
     */
    public MainMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        playgamebutton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(java.awt.Color.white);
        setName("mainmenuframe"); // NOI18N
        setPreferredSize(new java.awt.Dimension(800, 600));
        setResizable(false);

        gametitlelabel.setBackground(new java.awt.Color(255, 255, 255));
        gametitlelabel.setFont(new java.awt.Font("Bodoni MT Black", 0, 24)); // NOI18N
        gametitlelabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        gametitlelabel.setText("Game Title");
        gametitlelabel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        playgamebutton.setBackground(new java.awt.Color(153, 255, 255));
        playgamebutton.setText("Play Game");
        playgamebutton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        playgamebutton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        playgamebutton.setMargin(new java.awt.Insets(2, 15, 2, 15));
        playgamebutton.setMaximumSize(new java.awt.Dimension(100, 25));
        playgamebutton.setMinimumSize(new java.awt.Dimension(100, 25));
        playgamebutton.setPreferredSize(new java.awt.Dimension(100, 25));
        playgamebutton.setRolloverEnabled(false);
        playgamebutton.addActionListener(this);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(gametitlelabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(300, 300, 300)
                .addComponent(playgamebutton, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(300, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(gametitlelabel, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(playgamebutton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(377, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }

    // Code for dispatching events from components to event handlers.

    public void actionPerformed(java.awt.event.ActionEvent evt) {
        if (evt.getSource() == playgamebutton) {
            MainMenu.this.playgamebuttonActionPerformed(evt);
        }
    }// </editor-fold>//GEN-END:initComponents

    private void playgamebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playgamebuttonActionPerformed
        LaneGame.playGame();
        this.dispose();
    }//GEN-LAST:event_playgamebuttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private final javax.swing.JLabel gametitlelabel = new javax.swing.JLabel();
    private javax.swing.JButton playgamebutton;
    // End of variables declaration//GEN-END:variables
}
